In [2]:
import numpy as np

In [8]:
data = np.loadtxt('minutes_n_ingredients.csv', delimiter=',', skiprows=1, dtype=np.int32)
print("Первые 5 строк массива:\n", data[:5], sep='')

Первые 5 строк массива:
[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [162911     60     14]]


In [4]:
stats = [
    ('Среднее', np.mean),
    ('Минимум', np.min),
    ('Максимум', np.max),
    ('Медиана', np.median)
]

for name, func in stats:
    res = func(data[:, 1:], axis=0)
    print(f"{name}: время = {res[0]:.2f}, ингредиенты = {res[1]:.2f}")

Среднее: время = 21601.40, ингредиенты = 9.06
Минимум: время = 0.00, ингредиенты = 1.00
Максимум: время = 2147483647.00, ингредиенты = 39.00
Медиана: время = 40.00, ингредиенты = 9.00


In [5]:
q75 = np.quantile(data[:, 1], 0.75)
data[:, 1] = np.where(data[:, 1] > q75, q75, data[:, 1])

In [15]:
print(f"Рецептов с нулевой продолжительностью: {np.sum(data[:, 1] == 0)}")
data[:, 1] = np.where(data[:, 1] == 0, 1, data[:, 1])

Рецептов с нулевой продолжительностью: 479


In [16]:
print(f"Уникальных рецептов: {len(np.unique(data[:, 0]))}")

Уникальных рецептов: 98252


In [17]:
unique_ingredients, counts = np.unique(data[:, 2], return_counts=True)
print(f"Уникальные значения ингредиентов\n: {unique_ingredients}")
print(f"Количество значений:\n {counts}")

Уникальные значения ингредиентов
: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
Количество значений:
 [   13   926  2895  5515  7913  9376 10628 10951 10585  9591  8297  6605
  4997  3663  2595  1767  1246   790   573   376   217   161   105    69
    50    28    16    16    12    12     3     1     2     1     3     1
     1]


In [18]:
filtered_data = data[data[:, 2] <= 5]

In [24]:
print(f"Максимальное значение: {(data[:, 2] / data[:, 1]).max():.2f}")

Максимальное значение: 24.00


In [25]:
print(f"Среднее ингредиентов для топ-100: {(data[np.argsort(-data[:, 1])][:100])[:, 2].mean():.2f}")

Среднее ингредиентов для топ-100: 6.61


In [26]:
random_indices = np.random.choice(len(data), size=10, replace=False)
print(f"Случайные рецепты:\n{(data[random_indices])}")

Случайные рецепты:
[[290216     25      8]
 [380077     25      9]
 [462016     30      8]
 [ 34720     35      8]
 [283952      7      4]
 [401816     60      9]
 [318263     10      4]
 [291068    145     22]
 [290209     25      5]
 [519541      5      4]]


In [27]:
print(f"Процент рецептов: {np.sum(data[:, 2] < data[:, 2].mean()) / len(data) * 100:.2f}%")

Процент рецептов: 58.80%


In [28]:
is_simple = (data[:, 1] <= 20) & (data[:, 2] <= 5)
data_with_flag = np.column_stack((data, is_simple.astype(int)))
print(f"Процент простых рецептов: {is_simple.mean() * 100:.2f}%")

Процент простых рецептов: 9.55%


In [34]:
mask_short = data[:, 1] < 10
mask_standard = (data[:, 1] > 10) & (data[:, 1] < 20)
mask_long = data[:, 1] >= 20

groups = [
    data[mask_short],
    data[mask_standard],
    data[mask_long]
]

min_size = min(len(g) for g in groups)
arr3d = np.array([g[:min_size] for g in groups])
print("Форма 3D массива:", arr3d.shape)

Форма 3D массива: (3, 7588, 3)
